import type { Metadata } from "next";
import { Oswald } from 'next/font/google';
import "./globals.scss";
import { Footer } from '@/app/components/Footer';
import { NavBar } from '@/app/components/NavBar';

const oswald  = Oswald({
  weight: ['400', '700'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Nextflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={ `${ oswald.className }` }>
          <div className="navbar">
            <NavBar/>
          </div>
          <div className="navbar-offset">{ children }</div>
          <Footer></Footer>
        </body>
      </html>
  );
}
